### ISSUE TITLE
is there an ID that I can use in tests?

### ISSUE THREAD

**Issue by aymaneMx** [Moesif/moesifdjango#43]
Hi there!

I want to set up moesif to my Graphql API, but I faced some issues:
1. is there an ID I can use in my tests?
```
Unauthorized access getting application configuration. Please check your Appplication Id.
Response bytes body
```
2. some my tests failed with this error message, that I have no idea how to fix it:
```
ERROR    django.request:log.py:228 Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/moesifdjango/middleware.py", line 345, in __call__
    self.sampling_percentage = self.app_config.get_sampling_percentage(self.config, username, company_id)
  File "/usr/local/lib/python3.7/site-packages/moesifdjango/app_config.py", line 32, in get_sampling_percentage
    config_body = json.loads(config.raw_body)
AttributeError: 'NoneType' object has no attribute 'raw_body'
```
can you please help!

Thank you!!

**Comment by xinghengwang** [comment]
Create a free account on Moesif, then obtain the the application id in your account. thanks.

**Comment by aymaneMx** [comment]
I actually have an account, do you think that it okay to use my Application Id in tests too?

**Comment by aymaneMx** [comment]
thanks a lot guys!

please I have an other issue with saving files, just after I integrated **moesif** to my app

here is the error message I get :
`botocore.exceptions.ClientError: An error occurred (503) when calling the HeadBucket operation (reached max retries: 4): Service Unavailable`
the full traceback 👇 

```
______________________________________________________________________________________________ test_add_random_reply _______________________________________________________________________________________________

post = <Post: post>

    @pytest.mark.django_db
    def test_add_random_reply(post):
        post = post('text')
>       list_bots_ids = update_list_bots(bots_table)

tests/test_bot/test_bot.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
apps/utils/bot.py:78: in update_list_bots
    user, created = get_or_create_user(user_dict)
apps/utils/bot.py:60: in get_or_create_user
    user.photo.save(image.name, image, save=True)
/usr/local/lib/python3.7/site-packages/django/db/models/fields/files.py:87: in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
/usr/local/lib/python3.7/site-packages/django/core/files/storage.py:52: in save
    return self._save(name, content)
/usr/local/lib/python3.7/site-packages/storages/backends/s3boto3.py:542: in _save
    obj = self.bucket.Object(encoded_name)
/usr/local/lib/python3.7/site-packages/storages/backends/s3boto3.py:385: in bucket
    self._bucket = self._get_or_create_bucket(self.bucket_name)
/usr/local/lib/python3.7/site-packages/storages/backends/s3boto3.py:427: in _get_or_create_bucket
    bucket.meta.client.head_bucket(Bucket=name)
/usr/local/lib/python3.7/site-packages/botocore/client.py:357: in _api_call
    return self._make_api_call(operation_name, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <botocore.client.S3 object at 0x7fe3f8f02c18>, operation_name = 'HeadBucket', api_params = {'Bucket': 'media'}

    def _make_api_call(self, operation_name, api_params):
        operation_model = self._service_model.operation_model(operation_name)
        service_name = self._service_model.service_name
        history_recorder.record('API_CALL', {
            'service': service_name,
            'operation': operation_name,
            'params': api_params,
        })
        if operation_model.deprecated:
            logger.debug('Warning: %s.%s() is deprecated',
                         service_name, operation_name)
        request_context = {
            'client_region': self.meta.region_name,
            'client_config': self.meta.config,
            'has_streaming_input': operation_model.has_streaming_input,
            'auth_type': operation_model.auth_type,
        }
        request_dict = self._convert_to_request_dict(
            api_params, operation_model, context=request_context)
    
        service_id = self._service_model.service_id.hyphenize()
        handler, event_response = self.meta.events.emit_until_response(
            'before-call.{service_id}.{operation_name}'.format(
                service_id=service_id,
                operation_name=operation_name),
            model=operation_model, params=request_dict,
            request_signer=self._request_signer, context=request_context)
    
        if event_response is not None:
            http, parsed_response = event_response
        else:
            http, parsed_response = self._make_request(
                operation_model, request_dict, request_context)
    
        self.meta.events.emit(
            'after-call.{service_id}.{operation_name}'.format(
                service_id=service_id,
                operation_name=operation_name),
            http_response=http, parsed=parsed_response,
            model=operation_model, context=request_context
        )
    
        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (503) when calling the HeadBucket operation (reached max retries: 4): Service Unavailable

/usr/local/lib/python3.7/site-packages/botocore/client.py:661: ClientError
```

any idea? is there a conman error that I should expect?

Thanks.

**Comment by dgilling** [comment]
Hi @aymaneMx, I don't think we're able to help with the S3 access error. That seems like an exception unrelated to Moesif. You could try uninstall Moesif, but highly unlikely the two are related.
